from headbook.routes.index import *
from headbook.routes.login import *
from headbook.routes.logout import *
from headbook.routes.OAuth import *
from headbook.routes.signup import *
from headbook.routes.profile import *
from headbook.routes.buddies import *
from headbook.routes.buddies import *
from headbook.routes.users import *
from headbook.routes.current_user import *
from headbook.routes.misc import *
from headbook.routes.serve_static import *
